In [1]:
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier


# Decision Tree

In [19]:
# Define dataset path
dataset_dir = r"D:/machine learning files/archive (2)/Dataset"  # Replace with the actual path

# Initialize variables
images = []
labels = []

# Map classes to numeric labels
class_names = os.listdir(dataset_dir)  # ['class_1', 'class_2', 'class_3', 'class_4']
class_labels = {name: idx for idx, name in enumerate(class_names)}

# Load images and labels
for class_name, class_idx in class_labels.items():
    class_path = os.path.join(dataset_dir, class_name)
    for img_name in os.listdir(class_path):
        img_path = os.path.join(class_path, img_name)
        
        # Load and preprocess the image
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)  # Convert to grayscale
        img = cv2.resize(img, (256, 256))  # Resize to 64x64
        images.append(img.flatten())  # Flatten image into a 1D vector
        labels.append(class_idx)

# Convert to NumPy arrays
images = np.array(images)
labels = np.array(labels)

# Normalize the images
images = images / 255.0  # Scale pixel values to [0, 1]


In [20]:
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

In [4]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)


DecisionTreeClassifier()

In [5]:
y_pred = model.predict(X_test)

In [6]:
# Print evaluation metrics
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
accuracy = accuracy_score(y_pred,y_test)
print(f"accuracy: {accuracy}")


Classification Report:
              precision    recall  f1-score   support

         Bus       0.41      0.27      0.33        26
         Car       0.25      0.30      0.27        20
  motorcycle       0.17      0.13      0.15        15
       Truck       0.26      0.37      0.30        19

    accuracy                           0.28        80
   macro avg       0.27      0.27      0.26        80
weighted avg       0.29      0.28      0.27        80

Confusion Matrix:
[[7 6 6 7]
 [5 6 2 7]
 [2 5 2 6]
 [3 7 2 7]]
accuracy: 0.275


# KNN

In [7]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)


KNeighborsClassifier()

In [8]:
y_pred = knn.predict(X_test)

In [9]:
# Print evaluation metrics
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
accuracy = accuracy_score(y_pred,y_test)
print(f"accuracy: {accuracy}")


Classification Report:
              precision    recall  f1-score   support

         Bus       0.71      0.38      0.50        26
         Car       0.39      0.60      0.47        20
  motorcycle       0.31      0.53      0.39        15
       Truck       0.44      0.21      0.29        19

    accuracy                           0.42        80
   macro avg       0.46      0.43      0.41        80
weighted avg       0.49      0.42      0.42        80

Confusion Matrix:
[[10  9  7  0]
 [ 0 12  4  4]
 [ 2  4  8  1]
 [ 2  6  7  4]]
accuracy: 0.425


# Random Forest

In [10]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Predict on the test data
y_pred = rf_model.predict(X_test)

In [11]:
# Print evaluation metrics
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
accuracy = accuracy_score(y_pred,y_test)
print(f"accuracy: {accuracy}")


Classification Report:
              precision    recall  f1-score   support

         Bus       0.59      0.50      0.54        26
         Car       0.58      0.55      0.56        20
  motorcycle       0.47      0.60      0.53        15
       Truck       0.40      0.42      0.41        19

    accuracy                           0.51        80
   macro avg       0.51      0.52      0.51        80
weighted avg       0.52      0.51      0.51        80

Confusion Matrix:
[[13  3  7  3]
 [ 2 11  1  6]
 [ 0  3  9  3]
 [ 7  2  2  8]]
accuracy: 0.5125


# SVM (Support Vector Machine)

In [12]:
# Initialize and train the SVM model
svm_model = SVC(kernel='linear', C=1.0, random_state=42)  # Linear kernel for simplicity
svm_model.fit(X_train, y_train)

# Predict on the test data
y_pred = svm_model.predict(X_test)


In [13]:
# Print evaluation metrics
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
accuracy = accuracy_score(y_pred,y_test)
print(f"accuracy: {accuracy}")


Classification Report:
              precision    recall  f1-score   support

         Bus       0.61      0.42      0.50        26
         Car       0.38      0.65      0.48        20
  motorcycle       0.54      0.47      0.50        15
       Truck       0.33      0.26      0.29        19

    accuracy                           0.45        80
   macro avg       0.47      0.45      0.44        80
weighted avg       0.47      0.45      0.45        80

Confusion Matrix:
[[11  8  2  5]
 [ 1 13  2  4]
 [ 2  5  7  1]
 [ 4  8  2  5]]
accuracy: 0.45


# Naive Bais

In [14]:
# Initialize the Gaussian Naive Bayes classifier
nb_model = GaussianNB()

# Train the model
nb_model.fit(X_train, y_train)

# Predict on the test data
y_pred = nb_model.predict(X_test)


In [15]:
# Print evaluation metrics
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
accuracy = accuracy_score(y_pred,y_test)
print(f"accuracy: {accuracy}")


Classification Report:
              precision    recall  f1-score   support

         Bus       0.45      0.38      0.42        26
         Car       0.44      0.40      0.42        20
  motorcycle       0.38      0.20      0.26        15
       Truck       0.34      0.58      0.43        19

    accuracy                           0.40        80
   macro avg       0.40      0.39      0.38        80
weighted avg       0.41      0.40      0.39        80

Confusion Matrix:
[[10  3  3 10]
 [ 5  8  0  7]
 [ 1  7  3  4]
 [ 6  0  2 11]]
accuracy: 0.4


# Ada boost

In [16]:
# Define the base learner (Decision Tree Stump)
base_learner = DecisionTreeClassifier(max_depth=1)

# Initialize the AdaBoost classifier
adaboost_model = AdaBoostClassifier(base_estimator=base_learner, n_estimators=50, random_state=42)

# Train the AdaBoost model
adaboost_model.fit(X_train, y_train)

# Predict on the test data
y_pred = adaboost_model.predict(X_test)


D:\cnada\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


In [17]:
# Print evaluation metrics
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
accuracy = accuracy_score(y_pred,y_test)
print(f"accuracy: {accuracy}")


Classification Report:
              precision    recall  f1-score   support

         Bus       0.78      0.27      0.40        26
         Car       0.44      0.40      0.42        20
  motorcycle       0.56      0.33      0.42        15
       Truck       0.36      0.84      0.51        19

    accuracy                           0.45        80
   macro avg       0.54      0.46      0.44        80
weighted avg       0.55      0.45      0.43        80

Confusion Matrix:
[[ 7  4  2 13]
 [ 0  8  2 10]
 [ 0  5  5  5]
 [ 2  1  0 16]]
accuracy: 0.45


# Xg Boost

In [21]:
# Initialize the XGBoost Classifier
xgb_model = XGBClassifier(
    objective='multi:softmax',  # For multi-class classification
    num_class=4,               # Number of classes
    n_estimators=100,          # Number of boosting rounds
    learning_rate=0.1,         # Learning rate
    max_depth=6,               # Maximum depth of trees
    random_state=42
)

# Train the XGBoost model
xgb_model.fit(X_train, y_train)

# Predict on the test data
y_pred = xgb_model.predict(X_test)


In [22]:
# Print evaluation metrics
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
accuracy = accuracy_score(y_pred,y_test)
print(f"accuracy: {accuracy}")



Classification Report:
              precision    recall  f1-score   support

         Bus       0.43      0.46      0.44        26
         Car       0.55      0.60      0.57        20
  motorcycle       0.38      0.40      0.39        15
       Truck       0.36      0.26      0.30        19

    accuracy                           0.44        80
   macro avg       0.43      0.43      0.43        80
weighted avg       0.43      0.44      0.43        80

Confusion Matrix:
[[12  3  7  4]
 [ 2 12  3  3]
 [ 3  4  6  2]
 [11  3  0  5]]
accuracy: 0.4375
